[package]
name = "rust_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.0"
tobj = "4.0.2"
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
winit = { version = "0.28", default-features = true }
